version: "3.9"
services:
  local:
    profiles: [ "local" ]
    build: .
    image: boogaga2021/crystals_server:${TAG}
    extra_hosts:
      - "host:${HOST_LOCAL_VM}"
    container_name: ${SERVER_CONTAINER_NAME_1}
    ports:
      - "9350:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${HOST_LOCAL_VM}:5432/crystals

  local_vm:
    profiles: [ "local_vm" ]
    build: .
    image: boogaga2021/crystals_server:${TAG}
    extra_hosts:
      - "host:${HOST_LOCAL_VM}"
    container_name: ${SERVER_CONTAINER_NAME_1}
    ports:
      - "9350:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${HOST_LOCAL_VM}:5432/crystals

  remote_vm_1:
    profiles: [ "remote_vm" ]
    build: .
    image: boogaga2021/crystals_server:${TAG}
    extra_hosts:
      - "host:${HOST_REMOTE_VM}"
    container_name: ${SERVER_CONTAINER_NAME_1}
    ports:
      - "9350:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${HOST_REMOTE_VM}:5432/crystals
      - SERVER_PORT=8080

  remote_vm_2:
    profiles: [ "remote_vm" ]
    build: .
    image: boogaga2021/crystals_server:${TAG}
    extra_hosts:
      - "host:${HOST_REMOTE_VM}"
    container_name: ${SERVER_CONTAINER_NAME_2}
    ports:
      - "9351:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${HOST_REMOTE_VM}:5432/crystals
      - SERVER_PORT=8081