CREATE SEQUENCE global_seq AS INTEGER START WITH 1;

CREATE TABLE users
(
    id              INTEGER GENERATED BY DEFAULT AS SEQUENCE global_seq PRIMARY KEY,
    name            VARCHAR(50)                       NOT NULL,
    login           VARCHAR(50)                       NOT NULL,
    password        VARCHAR(200)                      NOT NULL,
    email           VARCHAR(50)                       NOT NULL,
    created         TIMESTAMP           DEFAULT now() NOT NULL,
    last_login_time TIMESTAMP                         NOT NULL,
    enabled         BOOLEAN             DEFAULT TRUE  NOT NULL,
    melee           INTEGER             DEFAULT 0     NOT NULL,
    melanges        INTEGER             DEFAULT 0     NOT NULL,
    solitaires      INTEGER             DEFAULT 0     NOT NULL,
    score           INTEGER             DEFAULT 0     NOT NULL,
    record          INTEGER             DEFAULT 0     NOT NULL,
    free_swaps      INTEGER             DEFAULT 0     NOT NULL,
    undo            INTEGER             DEFAULT 0     NOT NULL
);
CREATE UNIQUE INDEX users_unique_login_idx ON users (login);
CREATE UNIQUE INDEX users_unique_email_idx ON users (email);